---
# vars file for samba

samba_packages:
  - "samba"
  - "samba-client"

samba_configuration_dir: "/etc/samba"
samba_configuration: "{{ samba_configuration_dir }}/smb.conf"
samba_username_map_file: "{{ samba_configuration_dir }}/smbusers"

samba_services:
  - "smbd"
  - "nmbd"

samba_service_mgr: ""

# samba_www_documentroot: "/var/www"

samba_restart_handler_state: "restarted"